[project]
name = "docs"
version = "0.1.0"
description = ""
authors = [
    {name = "seungwonme",email = "seungwonan.me@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "crewai[tools] (>=0.95.0,<0.96.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
