[project]
name = "youtube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "langchain-community>=0.3.19",
    "pytube>=15.0.0",
    "youtube-transcript-api>=1.0.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
